name: ml_pp_mvp
description: Monaluxe Logistic Platform MVP
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  go_router: ^14.8.1
  supabase_flutter: ^2.6.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  intl: ^0.19.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - lib/shared/assets/images/logo.png
